package logic.usecase.audit

const val ADDED_ACTION = "added"
const val UPDATED_ACTION = "updated"
const val DELETED_ACTION = "deleted"
const val TASK_MESSAGE_TEMPLATE = "%s: %s '%s' (ID: %s) %s"
const val PROJECT_MESSAGE_TEMPLATE = "%s: %s '%s' (ID: %s) %s"
const val STATE_MESSAGE_TEMPLATE = "%s: %s '%s' (ID: %s)"
const val TASK_PROJECT_SUFFIX = "to the '%s' project"
const val PROJECT_STATE_SUFFIX = "with state '%s'"
const val COMBINED_DETAIL_FORMAT = "%s. %s."
const val TASK_NAME_UPDATE = "Task name from '%s' to '%s'"
const val PROJECT_NAME_UPDATE = "Project name from '%s' to '%s'"
const val STATE_NAME_UPDATE = "State name from '%s' to '%s'"
const val DESCRIPTION_UPDATE = "Description: '%s'"
const val STATE_UPDATED = "State: '%s'"
const val STATE_UPDATE_MESSAGE = "State: '%s'."