package org.example.logic.model.exceptions

class ReadDataException : Exception("Error while reading data!")
class WriteDataException : Exception("Error while writing data!")
class EmptyDataException : Exception("No data available")
class FileNotExistException : Exception("Error file not found!")
class NotAllowedStateNameException : Exception("Only letters are allowed!")
class InvalidUserName : Exception("Invalid userName")
class NoTasksFound : Exception("No Tasks found")
class TaskNotFoundException : Exception("No tasks found.")
class NoTaskAssignmentFound : Exception("No task assignments found.")
class NoTasksCreated : Exception("Failed to create task")
class NoTasksDeleted : Exception("Failed to delete task")
class StateNotExistException : Exception("The state does not exist")
class StateAlreadyExistException : Exception("The state already exists!")
class StateNameLengthException : Exception("The state name is too long!")
class NoStatesFoundedException : Exception("There are no states!")
class InvalidPassword : Exception("Invalid password")
class UserDoesNotExist : Exception("User does not exist")
class IncorrectPassword : Exception("Incorrect password")
class UsersDataAreEmpty : Exception("Users data are empty")
class UserExist : Exception("User already exists")
class NoObjectFound : Exception("The file is empty")
class ProjectNotFoundException : Exception("project Not Found")
class NoProjectAdded : Exception("No Project Added")
class InvalidUuid : Exception("Invalid Uuid")
