package org.example.logic.model.exceptions

class ReadDataException : Exception(message = "Error while reading data!")
class WriteDataException : Exception(message = "Error while writing data!")
class EmptyDataException : Exception(message = "No data available")
class FileNotExistException : Exception(message = "Error file not found!")
class NotAllowedStateNameException : Exception(message = "Only letters are allowed!")
class InvalidUserName : Exception(message = "Invalid userName")
class NoTasksFound : Exception(message = "No Tasks found")
class TaskNotFoundException : Exception(message = "No tasks found.")
class NoTaskAssignmentFound : Exception(message = "No task assignments found.")
class NoTasksCreated : Exception(message = "Failed to create task")
class NoTasksDeleted : Exception(message = "Failed to delete task")
class StateNotExistException : Exception(message = "The state does not exist")
class StateAlreadyExistException : Exception(message = "The state already exists!")
class StateNameLengthException : Exception(message = "The state name is too long!")
class NoStatesFoundedException : Exception(message = "There are no states!")
class InvalidPassword : Exception(message = "Invalid password")
class UserDoesNotExist : Exception(message = "User does not exist")
class IncorrectPassword : Exception(message = "Incorrect password")
class UsersDataAreEmpty : Exception(message = "Users data are empty")
class UserExist : Exception(message = "User already exists")
class NoObjectFound : Exception(message = "The file is empty")
class NoProjectAdded : Exception(message = "No Project Added")
