name: Java CI with Gradle

on:
  push:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This fetches the complete history including all branches

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport

      - name: Upload JaCoCo HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: build/reports/jacoco/test/html

      - name: Comment on coverage for current branch
        if: github.event_name == 'pull_request' && github.base_ref == 'develop'
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 100
          min-coverage-changed-files: 100
          update-comment: true
          title: "🛡️ Code Coverage Report"
          check-for-current-branch: true
          coverage-counter-type: LINE,INSTRUCTION,BRANCH,METHOD,CLASS
          include-all-sources: true
          debug-mode: true
          fail-if-coverage-less: true
          fail-on-coverage-violation: true
          failure-message: "Code coverage is currently at {coverage}%. Target is 100%."
          success-message: "✅ Code coverage is at {coverage}%."
          report-on-status: true

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
